Update script.yml

diff --git a/script.yml b/script.yml
--- a/script.yml
+++ b/script.yml
@@ -8,7 +8,6 @@ stages:
   - helm_argo_app
   - group_sync_and_git_push
 
-  
 variables:
   TAMPA_NAME: "Tampa"
   SAC_NAME: "Sacramento"
@@ -17,7 +16,7 @@ variables:
   SPOKE_SECRET_NS: appdev-gitops
 
 .helm_template:
-  image: 
+  image:
     name: docker-remote.oneartifactoryci.verizon.com/alpine/helm:3.10.2
     entrypoint: [""]
   needs:
@@ -34,26 +33,25 @@ variables:
     - echo $DATA_CENTER_URL
     - echo $DEV_AD_GROUPSx
     - echo $ADMIN_AD_GROUPSx
-    - cd nonprod 
-    - helm template $ENV-chart 
-     --dry-run -f $ENV-values.yaml 
-     --output-dir ./output/$DATA_CENTER/$VSAD/$APP/$ENV './' 
-     --set vsad=$VSAD
-     --set env=$ENV
-     --set appId=$APP 
-     --set serviceAccount.name=$SERVICEACCOUNT
-     --set tshirt=$TSHIRT
-     --set greenfield=$GREENFIELD
-     --set datacenter=$DATA_CENTER
-     --set datacenter_shortname=$DATA_CENTER_SHORT_NAME
-     --set datacenter_url=$DATA_CENTER_URL
-     --set "rolebindings.admin.subjects.name={$ADMIN_AD_GROUPSx}"
-     --set "rolebindings.dev.subjects.name={$DEV_AD_GROUPSx}"
-     --set uuid=$UUID
-     --set serviceAccountSecretNS=$SPOKE_SECRET_NS
-     --set "labels={$LABELSx}"
-     --set "annotations={$ANNOTATIONSx}"
-     #helm creates onboarding-pipeline folder, need to move newly created files out of that and into /vsad/app/env folder. then remove the onboarding-pipeline folder.
+    - cd nonprod
+    - helm template $ENV-chart \
+      --dry-run -f $ENV-values.yaml \
+      --output-dir ./output/$DATA_CENTER/$VSAD/$APP/$ENV './' \
+      --set vsad=$VSAD \
+      --set env=$ENV \
+      --set appId=$APP \
+      --set serviceAccount.name=$SERVICEACCOUNT \
+      --set tshirt=$TSHIRT \
+      --set greenfield=$GREENFIELD \
+      --set datacenter=$DATA_CENTER \
+      --set datacenter_shortname=$DATA_CENTER_SHORT_NAME \
+      --set datacenter_url=$DATA_CENTER_URL \
+      --set "rolebindings.admin.subjects.name={$ADMIN_AD_GROUPSx}" \
+      --set "rolebindings.dev.subjects.name={$DEV_AD_GROUPSx}" \
+      --set uuid=$UUID \
+      --set serviceAccountSecretNS=$SPOKE_SECRET_NS \
+      --set "labels={$LABELSx}" \
+      --set "annotations={$ANNOTATIONSx}"
     - mv ./output/$DATA_CENTER/$VSAD/$APP/$ENV/onboarding-pipeline/templates/* ./output/$DATA_CENTER/$VSAD/$APP/$ENV && rm -r ./output/$DATA_CENTER/$VSAD/$APP/$ENV/onboarding-pipeline/
     - cd ./output/$DATA_CENTER/$VSAD/$APP/$ENV
     - ls
@@ -64,70 +62,71 @@ variables:
     - mv argoEnvApp.yaml $VSAD-$ENV-$APP.yaml
     - cd ..
     - ls -ltra
-    - mv $ENV/$VSAD-$ENV-$APP.yaml . #for some reason, mving with pathing doesn't work here.
+    - mv $ENV/$VSAD-$ENV-$APP.yaml . #for some reason, moving with pathing doesn't work here.
   artifacts:
     name: "output"
     untracked: true
     paths:
       - output
-      - ./uuid.txt 
+      - ./uuid.txt
 
 helm_argo_app:
   stage: helm_argo_app
-  image: 
+  image:
     name: docker-remote.oneartifactoryci.verizon.com/alpine/helm:3.10.2
     entrypoint: [""]
   script:
-    - cd nonprod ##
-    - helm template argoapp-chart 
-     --dry-run -f $ENV-values.yaml './' 
-     --show-only templates/argoRootApp.yaml
-     --set vsad=$VSAD
-     --set env=$ENV
-     --set appId=$APP 
-     --set serviceAccount.name=$SERVICEACCOUNT 
-     --set tshirt=$TSHIRT 
-     --set serviceAccountSecretNS=$SPOKE_SECRET_NS
-     --set datacenter_url=$DATA_CENTER_URL
-     --set greenfield=$GREENFIELD --set datacenter=$DATA_CENTER --set datacenter_shortname=$DATA_CENTER_SHORT_NAME --set uuid=$UUID > ./output/$VSAD-$APP-nonprod-$DATA_CENTER.yaml
-     #helm creates onboarding-pipeline folder, need to move newly created files out of that and into /vsad/app/env folder. then remove the onboarding-pipeline folder.
+    - cd nonprod
+    - helm template argoapp-chart \
+      --dry-run -f $ENV-values.yaml './' \
+      --show-only templates/argoRootApp.yaml \
+      --set vsad=$VSAD \
+      --set env=$ENV \
+      --set appId=$APP \
+      --set serviceAccount.name=$SERVICEACCOUNT \
+      --set tshirt=$TSHIRT \
+      --set serviceAccountSecretNS=$SPOKE_SECRET_NS \
+      --set datacenter_url=$DATA_CENTER_URL \
+      --set greenfield=$GREENFIELD \
+      --set datacenter=$DATA_CENTER \
+      --set datacenter_shortname=$DATA_CENTER_SHORT_NAME \
+      --set uuid=$UUID > ./output/$VSAD-$APP-nonprod-$DATA_CENTER.yaml
   artifacts:
     name: "output"
     untracked: true
     paths:
       - output
-      - ./uuid.txt 
+      - ./uuid.txt
 
 group_sync_and_git_push:
   stage: group_sync_and_git_push
-  image: 
+  image:
     name: docker-remote.oneartifactoryci.verizon.com/alpine/git:latest
     entrypoint: [""]
   script:
     - echo $ENV
-    - cd nonprod/output/ #$DATA_CENTER
+    - cd nonprod/output/
     - ls
-    - git config --global user.email "Openshift.admins@verizon.com@verizon.com"
+    - git config --global user.email "Openshift.admins@verizon.com"
     - git config --global user.name "onboardingpipeline-bot"
     - git clone https://oauth2:$NONPROD_ACCESS_TOKEN@$MANIFEST_REPO
     - ls
     - cd onboarding_gitops_manifests_nonprod/groupsync/groups
-    # For each AD group, check file if exists. if it does not exist, add the group to the file
-    # helm treats whitespaces as a group, so need to be aware of that.
-    # if [ -z $(grep '[^[:space:]]' $file) ]; then ### check for empty or only has whitespaces in file
-    # echo -e "$(cat $file)$nl$admingroup" > $file ### Echo whole contents of file, add new line, add group. Print out everything to new file (not appending) -e allows for '\n'
     - |
       export IFS=","
       export nl="\n"
 
       export file=$CLUSTER_OC_NAME-uswin.data
+      if [ ! -f "$file" ]; then
+        echo "File $file not found!"
+        exit 1
+      fi
       for admingroup in $AD_DOMAIN_USWINx; do
-          if grep -Fxq "$admingroup" $file
-          then
+          if grep -Fxq "$admingroup" $file; then
               echo "$admingroup already in $file, skipping"
           else
               echo "adding $admingroup"
-              if [ -z $(grep '[^[:space:]]' $file) ]; then
+              if [ -z "$(grep '[^[:space:]]' $file)" ]; then
                   echo "empty file, adding $admingroup"
                   echo $admingroup > $file
               else
@@ -137,13 +136,16 @@ group_sync_and_git_push:
       done
 
       export file=$CLUSTER_OC_NAME-emea.data
+      if [ ! -f "$file" ]; then
+        echo "File $file not found!"
+        exit 1
+      fi
       for admingroup in $AD_DOMAIN_EMEAx; do
-          if grep -Fxq "$admingroup" $file
-          then
+          if grep -Fxq "$admingroup" $file; then
               echo "$admingroup already in $file, skipping"
           else
               echo "adding $admingroup"
-              if [ -z $(grep '[^[:space:]]' $file) ]; then
+              if [ -z "$(grep '[^[:space:]]' $file)" ]; then
                   echo "empty file, adding $admingroup"
                   echo $admingroup > $file
               else
@@ -153,13 +155,16 @@ group_sync_and_git_push:
       done
 
       export file=$CLUSTER_OC_NAME-adebp.data
+      if [ ! -f "$file" ]; then
+        echo "File $file not found!"
+        exit 1
+      fi
       for admingroup in $AD_DOMAIN_ADEBPx; do
-          if grep -Fxq "$admingroup" $file
-          then
+          if grep -Fxq "$admingroup" $file; then
               echo "$admingroup already in $file, skipping"
           else
               echo "adding $admingroup"
-              if [ -z $(grep '[^[:space:]]' $file) ]; then
+              if [ -z "$(grep '[^[:space:]]' $file)" ]; then
                   echo "empty file, adding $admingroup"
                   echo $admingroup > $file
               else
@@ -167,15 +172,18 @@ group_sync_and_git_push:
               fi
           fi
       done
-      
+
       export file=$CLUSTER_OC_NAME-vdsi.data
+      if [ ! -f "$file" ]; then
+        echo "File $file not found!"
+        exit 1
+      fi
       for admingroup in $AD_DOMAIN_VDSIx; do
-          if grep -Fxq "$admingroup" $file
-          then
+          if grep -Fxq "$admingroup" $file; then
               echo "$admingroup already in $file, skipping"
           else
               echo "adding $admingroup"
-              if [ -z $(grep '[^[:space:]]' $file) ]; then
+              if [ -z "$(grep '[^[:space:]]' $file)" ]; then
                   echo "empty file, adding $admingroup"
                   echo $admingroup > $file
               else
@@ -192,15 +200,15 @@ group_sync_and_git_push:
     - git commit -m "push nonprod $VSAD/$APP/$ENV from pipeline"
     - git push origin HEAD:main
   artifacts:
-     paths:
-       - ./uuid.txt
+    paths:
+      - ./uuid.txt
 
 helm_dev:
   stage: helm_dev
   extends: .helm_template
   only:
-    variables: 
-      - $DEV == "true"  
+    variables:
+      - $DEV == "true"
   variables:
     ENV: dev
   script:
@@ -214,8 +222,8 @@ helm_qa:
   stage: helm_qa
   extends: .helm_template
   only:
-    variables: 
-      - $QA == "true"  
+    variables:
+      - $QA == "true"
   variables:
     ENV: qa
   script:
@@ -229,7 +237,7 @@ helm_sit:
   stage: helm_sit
   extends: .helm_template
   only:
-    variables: 
+    variables:
       - $SIT == "true"
   variables:
     ENV: sit
@@ -244,8 +252,8 @@ helm_stg:
   stage: helm_stg
   extends: .helm_template
   only:
-    variables: 
-      - $STG == "true"  
+    variables:
+      - $STG == "true"
   variables:
     ENV: stg
   script:
@@ -259,8 +267,8 @@ helm_uat:
   stage: helm_uat
   extends: .helm_template
   only:
-    variables: 
-      - $UAT == "true"  
+    variables:
+      - $UAT == "true"
   variables:
     ENV: uat
   script:
@@ -274,8 +282,8 @@ helm_pre_prod:
   stage: helm_pre_prod
   extends: .helm_template
   only:
-    variables: 
-      - $PREPROD == "true"  
+    variables:
+      - $PREPROD == "true"
   variables:
     ENV: preprod
   script:
@@ -283,4 +291,4 @@ helm_pre_prod:
     - echo "ENV=$ENV" >> myVars.env
   artifacts:
     reports:
-      dotenv: myVars.env      
+      dotenv: myVars.env
